version: '3'
services:
  ############################
  # person app + Dapr sidecar
  ############################
  person:
    build: ./person
    command: ["./person"]
    ports:
      - "50007:50007"
    depends_on:
      - placement
    networks:
      - service-network
  person-dapr:
    image: "daprio/daprd:1.3.0"
    command: ["./daprd",
     "-app-id", "person",
     "--app-port", "50051",
     "--dapr-grpc-port", "50007",
     "--app-protocol", "grpc",
     "--config", "/manifests/previewConfig.yaml",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
      - "./manifests/:/manifests"
    depends_on:
      - person
    network_mode: "service:person"
  ############################
  # grpcui + Dapr sidecar
  ############################
  grpcui:
    build: ./grpcui
    command: ["grpcui", 
      "-plaintext",
      "-bind", "0.0.0.0",
      "-port", "8080",
      "-import-path", "/proto",
      "-proto", "service.proto",
      "grpcui-dapr:50007"]
    ports:
      - "8080:8080"
    depends_on:
      - placement
      - grpcui-dapr
    volumes:
      - "./person/proto:/proto"
    networks:
      - service-network
  # used for gRPC server for gRPC UI
  grpcui-dapr:
    image: "daprio/daprd:1.3.0"
    command: ["./daprd",
     "-app-id", "grpcui",
     "--dapr-grpc-port", "50007",
     "--app-protocol", "grpc",
     "--config", "/manifests/previewConfig.yaml",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
      - "./manifests/:/manifests"
    networks:
      - service-network
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr:1.3.0"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - service-network
networks:
    service-network: