// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type CreateResponse struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*CreateRequest)(nil), "person.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "person.CreateResponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0x6d, 0x4f, 0x03, 0x3e, 0xb9, 0x22, 0x4f, 0x94, 0xe2, 0x74, 0x74, 0x90, 0x5b, 0x2e,
	0x91, 0x8a, 0xa0, 0x8b, 0x83, 0x6e, 0x4e, 0x12, 0x37, 0xb7, 0x5c, 0xfb, 0xa8, 0x01, 0x9b, 0xc4,
	0x24, 0x15, 0xfc, 0xef, 0xc5, 0xe4, 0x4e, 0xd1, 0x9b, 0xf2, 0x7d, 0x5f, 0xf2, 0x4b, 0xbe, 0x3c,
	0x38, 0x71, 0xde, 0x46, 0x2b, 0x02, 0xf9, 0x0f, 0xdd, 0x11, 0x4f, 0x0e, 0x99, 0x23, 0x1f, 0xac,
	0x69, 0xee, 0x80, 0x3d, 0x25, 0x85, 0x15, 0x94, 0xba, 0xaf, 0x8b, 0x45, 0xb1, 0x3c, 0x90, 0xa5,
	0xee, 0x11, 0x61, 0xdf, 0xa8, 0x91, 0xea, 0x72, 0x51, 0x2c, 0x0f, 0x65, 0xd2, 0x78, 0x0c, 0x33,
	0x35, 0x50, 0x3d, 0x4b, 0x87, 0xbe, 0x65, 0x73, 0x0d, 0xf3, 0x07, 0x4f, 0x2a, 0x92, 0xa4, 0xf7,
	0x89, 0x42, 0xfc, 0xc1, 0x8a, 0x5d, 0xac, 0xfc, 0xc5, 0x6e, 0xa0, 0xda, 0x62, 0xc1, 0x59, 0x13,
	0x08, 0x2f, 0x60, 0x53, 0x29, 0x91, 0x47, 0x6d, 0xc5, 0xb3, 0xe5, 0xb9, 0x9e, 0xdc, 0xec, 0xb6,
	0x8f, 0x30, 0xcf, 0xc9, 0x73, 0xfe, 0x0f, 0xde, 0x02, 0xcb, 0x57, 0xe1, 0xe9, 0x16, 0xf9, 0xd3,
	0xe8, 0xfc, 0xec, 0x7f, 0x9c, 0x5f, 0x6c, 0xf6, 0xee, 0xdb, 0x97, 0xcb, 0x41, 0xc7, 0xd7, 0x69,
	0xcd, 0x3b, 0x3b, 0x8a, 0xf0, 0x39, 0x39, 0xe5, 0x8d, 0xe8, 0x95, 0xf3, 0xab, 0xc1, 0xbb, 0x6e,
	0x15, 0xd4, 0xe8, 0xde, 0x48, 0x64, 0x5c, 0xa4, 0xc1, 0xad, 0x59, 0x5a, 0xae, 0xbe, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x08, 0xc7, 0x36, 0x17, 0x56, 0x01, 0x00, 0x00,
}
