// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type CreateResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "person.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "person.CreateResponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x4b, 0xc6, 0x30,
	0x10, 0x86, 0x6d, 0x3e, 0xbf, 0x80, 0x07, 0x16, 0x89, 0x28, 0xc5, 0xa9, 0x74, 0xea, 0xd2, 0x44,
	0x2a, 0x0e, 0xae, 0x16, 0x9c, 0x25, 0xa3, 0x5b, 0xda, 0x1e, 0x35, 0x60, 0x93, 0x98, 0xa4, 0x82,
	0xff, 0x5e, 0x4c, 0xb0, 0xa0, 0x4e, 0x79, 0x73, 0xf0, 0x3e, 0xf7, 0x1c, 0x5c, 0x3a, 0x6f, 0xa3,
	0x15, 0x01, 0xfd, 0x87, 0x9e, 0x90, 0xa7, 0x1f, 0xa3, 0x0e, 0x7d, 0xb0, 0xa6, 0xb9, 0x87, 0xf3,
	0xc1, 0xa3, 0x8a, 0x28, 0xf1, 0x7d, 0xc3, 0x10, 0x19, 0x83, 0x53, 0xa3, 0x56, 0xac, 0x8a, 0xba,
	0x68, 0xcf, 0x64, 0xca, 0xec, 0x02, 0x0e, 0x6a, 0xc1, 0x8a, 0xd4, 0x45, 0x7b, 0x94, 0xdf, 0xb1,
	0x79, 0x82, 0xf2, 0xa7, 0x16, 0x9c, 0x35, 0x01, 0x59, 0x09, 0x44, 0xcf, 0xa9, 0x75, 0x94, 0x44,
	0xcf, 0x3b, 0x87, 0xfc, 0xe7, 0x1c, 0x76, 0x4e, 0x3f, 0x00, 0x7d, 0x4e, 0x22, 0xec, 0x01, 0x68,
	0x26, 0xb2, 0x2b, 0x9e, 0xdd, 0xf8, 0x2f, 0xb1, 0x9b, 0xeb, 0xbf, 0xe3, 0xbc, 0xb8, 0x39, 0x79,
	0xec, 0x5f, 0x6e, 0x17, 0x1d, 0x5f, 0xb7, 0x91, 0x4f, 0x76, 0x15, 0xe1, 0x73, 0x73, 0xca, 0x1b,
	0x31, 0x2b, 0xe7, 0xbb, 0xc5, 0xbb, 0xa9, 0x0b, 0x6a, 0x75, 0x6f, 0x28, 0x72, 0x5d, 0xa4, 0xfb,
	0x47, 0x9a, 0x9e, 0xbb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x98, 0x47, 0x30, 0x1d, 0x01,
	0x00, 0x00,
}
