// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Drink int32

const (
	Drink_DRINK_UNKNOWN      Drink = 0
	Drink_DRINK_BEER         Drink = 1
	Drink_DRINK_COKE         Drink = 2
	Drink_DRINK_TEA          Drink = 3
	Drink_DRINK_ORANGE_JUICE Drink = 4
)

var Drink_name = map[int32]string{
	0: "DRINK_UNKNOWN",
	1: "DRINK_BEER",
	2: "DRINK_COKE",
	3: "DRINK_TEA",
	4: "DRINK_ORANGE_JUICE",
}

var Drink_value = map[string]int32{
	"DRINK_UNKNOWN":      0,
	"DRINK_BEER":         1,
	"DRINK_COKE":         2,
	"DRINK_TEA":          3,
	"DRINK_ORANGE_JUICE": 4,
}

func (x Drink) String() string {
	return proto.EnumName(Drink_name, int32(x))
}

func (Drink) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

type Order struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Drink                Drink                  `protobuf:"varint,2,opt,name=drink,proto3,enum=order.Drink" json:"drink,omitempty"`
	Time                 *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetDrink() Drink {
	if m != nil {
		return m.Drink
	}
	return Drink_DRINK_UNKNOWN
}

func (m *Order) GetTime() *timestamppb.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type CreateRequest struct {
	Drink                Drink    `protobuf:"varint,1,opt,name=drink,proto3,enum=order.Drink" json:"drink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetDrink() Drink {
	if m != nil {
		return m.Drink
	}
	return Drink_DRINK_UNKNOWN
}

type CreateResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterEnum("order.Drink", Drink_name, Drink_value)
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*CreateRequest)(nil), "order.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "order.CreateResponse")
	proto.RegisterType((*ListRequest)(nil), "order.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "order.ListResponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0xeb, 0x9b, 0x40,
	0x14, 0xfc, 0x69, 0x62, 0x20, 0x2f, 0x51, 0xec, 0xa6, 0x2d, 0xe2, 0xa5, 0x22, 0x3d, 0x84, 0x42,
	0x56, 0xf2, 0x01, 0x3d, 0xe7, 0x43, 0x4a, 0x9a, 0xa2, 0xb0, 0x4d, 0x28, 0xf4, 0x12, 0x4c, 0xdc,
	0x5a, 0x49, 0x8c, 0x76, 0x57, 0x0b, 0xed, 0x5f, 0x5f, 0xdc, 0xd5, 0xa6, 0x69, 0xe9, 0x49, 0x66,
	0xde, 0xcc, 0x9b, 0x37, 0x2a, 0x8c, 0x0a, 0x96, 0x97, 0xb9, 0xc7, 0x29, 0xfb, 0x9e, 0x9e, 0x29,
	0x16, 0x08, 0x69, 0x39, 0x8b, 0x29, 0xb3, 0x5f, 0x25, 0x79, 0x9e, 0x5c, 0xa9, 0x27, 0xc8, 0x53,
	0xf5, 0xc5, 0x2b, 0xd3, 0x8c, 0xf2, 0x32, 0xca, 0x0a, 0xa9, 0x73, 0x2f, 0xa0, 0x85, 0xb5, 0x12,
	0x19, 0xa0, 0xa6, 0xb1, 0xa5, 0x38, 0xca, 0xb8, 0x4f, 0xd4, 0x34, 0x46, 0x2e, 0x68, 0x31, 0x4b,
	0x6f, 0x17, 0x4b, 0x75, 0x94, 0xb1, 0x31, 0x1b, 0x62, 0xb1, 0x10, 0x6f, 0x6a, 0x8e, 0xc8, 0x11,
	0xc2, 0xd0, 0xad, 0xf7, 0x59, 0x1d, 0x47, 0x19, 0x0f, 0x66, 0x36, 0x96, 0x61, 0xb8, 0x0d, 0xc3,
	0xfb, 0x36, 0x8c, 0x08, 0x9d, 0x3b, 0x07, 0x7d, 0xcd, 0x68, 0x54, 0x52, 0x42, 0xbf, 0x55, 0x94,
	0x97, 0xf7, 0x10, 0xe5, 0xbf, 0x21, 0xee, 0x02, 0x8c, 0xd6, 0xc4, 0x8b, 0xfc, 0xc6, 0x69, 0xed,
	0x12, 0x3a, 0xe1, 0x1a, 0xfc, 0x76, 0x89, 0x1e, 0x44, 0x8e, 0x5c, 0x1d, 0x06, 0x1f, 0x52, 0x5e,
	0x36, 0x41, 0xee, 0x02, 0x86, 0x12, 0x36, 0x2b, 0x5e, 0x43, 0x4f, 0xe8, 0xb8, 0xa5, 0x38, 0x9d,
	0x7f, 0x76, 0x34, 0xb3, 0x37, 0x11, 0x68, 0xe2, 0x14, 0xf4, 0x0c, 0xf4, 0x0d, 0xd9, 0x06, 0xbb,
	0xe3, 0x21, 0xd8, 0x05, 0xe1, 0xa7, 0xc0, 0x7c, 0x42, 0x06, 0x80, 0xa4, 0x56, 0xbe, 0x4f, 0x4c,
	0xe5, 0x8e, 0xd7, 0xe1, 0xce, 0x37, 0x55, 0xa4, 0x43, 0x5f, 0xe2, 0xbd, 0xbf, 0x34, 0x3b, 0xe8,
	0x25, 0x20, 0x09, 0x43, 0xb2, 0x0c, 0xde, 0xf9, 0xc7, 0xf7, 0x87, 0xed, 0xda, 0x37, 0xbb, 0xb3,
	0x9f, 0x30, 0x14, 0x99, 0x1f, 0xe5, 0xd7, 0x43, 0x6f, 0xa1, 0x27, 0xdb, 0xa2, 0xe7, 0xcd, 0x49,
	0x0f, 0x6f, 0xcc, 0x7e, 0xf1, 0x17, 0x2b, 0xfb, 0xb8, 0x4f, 0x68, 0x0a, 0xdd, 0xba, 0x21, 0x42,
	0x8d, 0xe0, 0x8f, 0xf6, 0xf6, 0xe8, 0x81, 0x6b, 0x2d, 0xab, 0xe9, 0x67, 0x2f, 0x49, 0xcb, 0xaf,
	0xd5, 0x09, 0x9f, 0xf3, 0xcc, 0xe3, 0x3f, 0xaa, 0x22, 0x62, 0x37, 0x2f, 0x8e, 0x0a, 0x36, 0x49,
	0x58, 0x71, 0x9e, 0xf0, 0x28, 0x2b, 0xae, 0xd4, 0x13, 0xde, 0xe6, 0x0f, 0xea, 0x89, 0xc7, 0xfc,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x2c, 0x93, 0xcf, 0x74, 0x02, 0x00, 0x00,
}
